---
# tasks file for hello-world

- name: Stop apache
  service:
    name: apache2
    state: stopped

- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Copy Nginx conf
  copy:
    src: hello-world
    dest: /etc/nginx/sites-available/hello-world

- name: Symlink hello-world in sites-enabled
  file:
    state: link
    src: /etc/nginx/sites-available/hello-world
    dest: /etc/nginx/sites-enabled/hello-world

- name: Create html folder
  file:
    state: directory
    path: /opt/hello-world
    owner: www-data
    group: www-data

- name: Render from template index.html
  template:
    src: index.html.j2
    dest: /opt/hello-world/index.html
    owner: www-data
    group: www-data

- name: Start nginx
  service:
    name: nginx
    state: restarted
